spring.application.name=fluxbank-api

server.port=8080

# Carrega o arquivo .env localizado na raiz da pasta backend.
# O arquivo é opcional porque as variáveis também poderão vir do sistema operacional.
spring.config.import=optional:file:./.env[extension=.properties]

# PostgreSQL
spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# O Hibernate apenas valida a estrutura existente.
# A criação e alteração das tabelas será responsabilidade do Flyway.
spring.jpa.hibernate.ddl-auto=validate

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# Proteção de dados sensíveis
app.crypto.encryption-key=${APP_CRYPTO_ENCRYPTION_KEY}
app.crypto.hmac-key=${APP_CRYPTO_HMAC_KEY}
app.crypto.key-version=${APP_CRYPTO_KEY_VERSION:1}