spring.application.name=fluxbank-api

# Desabilita temporariamente banco, JPA e Flyway
# Usado apenas enquanto ainda não configuramos o PostgreSQL
spring.autoconfigure.exclude=\
org.springframework.boot.jdbc.autoconfigure.DataSourceAutoConfiguration,\
org.springframework.boot.hibernate.autoconfigure.HibernateJpaAutoConfiguration,\
org.springframework.boot.flyway.autoconfigure.FlywayAutoConfiguration

server.port=8080